# Qdrant configuration for production deployment
service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  enable_cors: true
  
  # Performance settings
  max_request_size_mb: 32
  max_workers: 0  # Auto-detect based on CPU cores
  
storage:
  # Storage optimization
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots
  
  # Performance tuning
  wal_capacity_mb: 64
  wal_segments_ahead: 0
  
  # Memory optimization
  memmap_threshold_kb: 1048576  # 1GB
  indexing_threshold_kb: 20971520  # 20GB
  
  # Persistence settings
  performance:
    max_search_requests: 100
    search_timeout_ms: 30000
  
  # Replication settings
  on_disk_payload: true
  
telemetry:
  disabled: false

cluster:
  enabled: false

log_level: INFO